server:
  port: 8103
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/warehouse?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
